name: Keepalive
run-name: Keep repository active so scheduled workflows aren't auto-disabled
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
